using BinaryWPF.Properties;
using BinaryWPF.Services;

using CoreExtensions.IO;
using CoreExtensions.Management;
using CoreExtensions.Native;

using Endscript.Core;

using System;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Security.Principal;
using System.Threading;
using System.Windows;
using Application = System.Windows.Application;
using MessageBox = System.Windows.MessageBox;

namespace BinaryWPF
{
    public partial class App : Application
    {
        private bool _debugMode;

        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

#if DEBUG
            _debugMode = true;
#endif

            if (Configurations.Default.UpgradeRequired)
            {
                Configurations.Default.Upgrade();
                Configurations.Default.UpgradeRequired = false;
                Configurations.Default.Save();
            }

            if (_debugMode || e.Args.Length > 0)
            {
                NativeCallerX.AllocConsole();
            }
            else if (!Debugger.IsAttached && !Configurations.Default.DisableAdminWarning)
            {
                using var identity = WindowsIdentity.GetCurrent();
                var principal = new WindowsPrincipal(identity);

                if (!principal.IsInRole(WindowsBuiltInRole.Administrator))
                {
                    MessageBox.Show(
                        "Binarius is currently running in User Mode. To prevent issues while working with games installed in restricted places, it's highly recommended to run Binarius as Administrator.",
                        "Warning",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);
                }
            }

            var culture = CultureInfo.CreateSpecificCulture("en-US");
            Thread.CurrentThread.CurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;

            var version = Assembly.GetExecutingAssembly().GetName().Version;
            Endscript.Version.Value = version;
            SynchronizedDatabase.Watermark = "Binarius | Automated";

            EnsureLogFiles();
            SetDependencyPaths(AppDomain.CurrentDomain.BaseDirectory);

            DispatcherUnhandledException += (_, args) =>
            {
                var logger = new Logger("MainLog.txt", "Binarius : Unknown Exception", true);
                logger.WriteException(args.Exception);
                logger.Dispose();

#if DEBUG
                MessageBox.Show(
                    "Unexpected error has occured. Please send MainLog.txt file to us. " +
                    "Right now Binarius will export all your collections to an autogenerated folder so you won't lose your data.",
                    "Warning",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
#else
                MessageBox.Show(
                    $"Unexpected error has occured: {args.Exception.GetLowestMessage()}",
                    "Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
#endif

                args.Handled = true;
            };

            if (e.Args.Length > 0)
            {
                var cli = new CliRunner();
                cli.Run(e.Args);

                if (_debugMode)
                {
                    NativeCallerX.FreeConsole();
                }

                Shutdown(0);
                return;
            }

            var themeService = new ThemeService();
            themeService.ApplyThemeResources();

            var window = new Views.IntroWindow();
            MainWindow = window;
            window.Show();
        }

        private static void EnsureLogFiles()
        {
            if (!File.Exists("MainLog.txt"))
            {
                using var _ = File.Create("MainLog.txt");
            }

            if (!File.Exists("EndError.log"))
            {
                using var _ = File.Create("EndError.log");
            }
        }

        private static void SetDependencyPaths(string basePath)
        {
            var userdir = Path.Combine(basePath, "userkeys");
            var mainc = Path.Combine(basePath, @"mainkeys\carbon.txt");
            var userc = Path.Combine(basePath, @"userkeys\carbon.txt");
            var mainmw = Path.Combine(basePath, @"mainkeys\mostwanted.txt");
            var usermw = Path.Combine(basePath, @"userkeys\mostwanted.txt");
            var mainps = Path.Combine(basePath, @"mainkeys\prostreet.txt");
            var userps = Path.Combine(basePath, @"userkeys\prostreet.txt");
            var mainuc = Path.Combine(basePath, @"mainkeys\undercover.txt");
            var useruc = Path.Combine(basePath, @"userkeys\undercover.txt");
            var mainug1 = Path.Combine(basePath, @"mainkeys\underground1.txt");
            var userug1 = Path.Combine(basePath, @"userkeys\underground1.txt");
            var mainug2 = Path.Combine(basePath, @"mainkeys\underground2.txt");
            var userug2 = Path.Combine(basePath, @"userkeys\underground2.txt");
            var usercustattr = Path.Combine(basePath, @"userkeys\CustomAttributes.txt");

            Endscript.Profiles.CarbonProfile.MainHashList = mainc;
            Endscript.Profiles.CarbonProfile.CustomHashList = userc;
            Endscript.Profiles.MostWantedProfile.MainHashList = mainmw;
            Endscript.Profiles.MostWantedProfile.CustomHashList = usermw;
            Endscript.Profiles.ProstreetProfile.MainHashList = mainps;
            Endscript.Profiles.ProstreetProfile.CustomHashList = userps;
            Endscript.Profiles.UndercoverProfile.MainHashList = mainuc;
            Endscript.Profiles.UndercoverProfile.CustomHashList = useruc;
            Endscript.Profiles.Underground1Profile.MainHashList = mainug1;
            Endscript.Profiles.Underground1Profile.CustomHashList = userug1;
            Endscript.Profiles.Underground2Profile.MainHashList = mainug2;
            Endscript.Profiles.Underground2Profile.CustomHashList = userug2;
            Nikki.Core.Map.CustomAttribFile = usercustattr;

            if (!Directory.Exists(userdir))
            {
                _ = Directory.CreateDirectory(userdir);
            }

            if (!File.Exists(userc)) { _ = File.Create(userc); }
            if (!File.Exists(usermw)) { _ = File.Create(usermw); }
            if (!File.Exists(userps)) { _ = File.Create(userps); }
            if (!File.Exists(useruc)) { _ = File.Create(useruc); }
            if (!File.Exists(userug1)) { _ = File.Create(userug1); }
            if (!File.Exists(userug2)) { _ = File.Create(userug2); }
            if (!File.Exists(usercustattr)) { _ = File.Create(usercustattr); }
        }
    }
}
